print('KFC is the world's best burger')
print('KFC is the world's best burger')
print('KFC is the world's best burger')
print('KFC is the world's best burger')
print('KFC is the world's best burger')
